### ISSUE TITLE
AssertIsTrue: Simplify Assertion does not offer automatic fix to apply

### ISSUE THREAD

**Issue by robertMSFTE** [fluentassertions/fluentassertions.analyzers#160]
### Description

AssertIsTrue: Simplify Assertion does not offer automatic fix to apply.

### Complete minimal example reproducing the issue

This gets a suggestion but there is no fix shown to apply in VS.

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.IsTrue(true);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/82510566/161642022-1e5a628a-6dd7-4687-8f60-d00ba45c036c.png)

### Expected behavior:

Fix suggestion should be shown.

### Actual behavior:

Fix suggestion is not shown.

### Versions

* Which version of Fluent Assertions Analyzers are you using? FluentAssertions.Analyzers  0.17.2
* Which .NET runtime and version are you targeting? .NET Core 3.1.

**Comment by Meir017** [comment]
I think the fix here should be to not trigger the analyzer since asserting a constant value does not do anything

**Comment by robertMSFTE** [comment]
@Meir017 This was just an example. The issue is that in general the fix never seems to be shown for this rule.

Example without a constant:

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.IsTrue(ComputeSomething());
        }

        private bool ComputeSomething()
        {
            return true;
        }
    }
}
```

**Comment by Meir017** [comment]
Now this is interesting 🤔

**Comment by robertMSFTE** [comment]
Today I got this (which probably is related to why the fix does not work):
![image](https://user-images.githubusercontent.com/82510566/203112057-38db9ddd-e62b-46b3-bc75-7502a1829b34.png)

_System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax'.
   at async FluentAssertions.Analyzers.FluentAssertionsCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)_

**Comment by Meir017** [comment]
@robertMSFTE can you share a minimal code sample to reproduce this error?

**Comment by robertMSFTE** [comment]
I saw this only once so far. Will add a repro if I get this to reproduce.

**Comment by MisinformedDNA** [comment]
I'm seeing a similar issue for xUnit.

![image](https://github.com/fluentassertions/fluentassertions.analyzers/assets/1784452/12f8662c-10a2-4892-8010-07d3c7658d2d)

I get a recommendation outside of a block, but not inside:

```
[Fact]
public void SomeTest()
{
    bool result = false;
    Assert.True(result);

    if (true)
    {
        Assert.True(result);
    }

    while (true)
    {
        Assert.True(result);
    }
}
```

**Comment by Meir017** [comment]
resolved by #167

**Comment by robertMSFTE** [comment]
@Meir017 The scenario still reproduces on ``0.20.0`` - aka. there is no fix suggestion.

**Comment by kimpenhaus** [comment]
@Meir017 we are running with `FluentAssertions.Analyzers 0.24.0` and having the same behavior

`Àssert.IsTrue / Assert.IsFalse` only shows the suggestion but not the quix fix:

<img width="1784" alt="image" src="https://github.com/fluentassertions/fluentassertions.analyzers/assets/575109/5d444c87-fd71-4204-9c5f-af5954ce4068">

While others do:

<img width="948" alt="image" src="https://github.com/fluentassertions/fluentassertions.analyzers/assets/575109/b98ead57-25e9-4781-9ab3-1a055db1a55e">

Running inside Rider IDE 2023.2.2 and using .NET 7.0.401 (OSX 14.0)

**Comment by kimpenhaus** [comment]
@Meir017 
I could reporduce this with the simplest Test possible - not sure if that helps you but I've attached that as an sample. First I thought it might some sort of constellation with other analyzers or a more complex environment but it seems it also happens with only the things needed to run the tests under MSTest.

I appreciate the time you'll spend - thanks for that 🙏🏼 

[ConsoleApp2.zip](https://github.com/fluentassertions/fluentassertions.analyzers/files/12783944/ConsoleApp2.zip)

**Comment by Meir017** [comment]
@kimpenhaus @robertMSFTE please check in version `0.25.0`

**Comment by kimpenhaus** [comment]
@Meir017 

yay - that looks good - thanks for the quick fix

<img width="500" alt="image" src="https://github.com/fluentassertions/fluentassertions.analyzers/assets/575109/0df291c2-3071-4e74-a0d1-a6987f93d3d7">
